### ISSUE TITLE
GroupMenuController's constructor is not compatible with GroupContentController

### ISSUE THREAD

**Issue by misterjoonas** [awalacabab/group_menu#3]
I get the following error on every drush cache rebuild:

```
Declaration of Drupal\group_menu\Controller\GroupMenuController::addPageBundleMessage(Drupal\group\Entity\GroupInterface $group) should [warning]
be compatible with Drupal\group\Entity\Controller\GroupContentController::addPageBundleMessage(Drupal\group\Entity\GroupInterface
$group, $create_mode) in include() (line 414 of /vagrant/drupal/current/vendor/composer/ClassLoader.php). include() (Line: 414)
Composer\Autoload\includeFile(&#039;/vagrant/drupal/current/web/modules/contrib/groupmenu/src/Controller/GroupMenuController.php&#039;)
(Line: 301)
```

I'm not sure, but it looks like GroupMenuController's constructor doesn't define PrivateTempStoreFactory $temp_store_factory variable which GroupContentController does.

Also the addPageBundles and addPageBundleMessage are missing the $create_mode variable in declaration.

**Comment by maebug** [comment]
This is a consequence of both group and group menu being under active development at the same time. In the previous version of group, this would work. In the latest version of group, it does not.

Perhaps once group and/or groupmenu gets a full release we should try and work with the maintainer(s) of group about giving us a couple days of lead time to keep up to date with their code. I would suspect (and hope) that such significant changes in model constructors don't happen too often with a full release. But I guess you never really know.

Anyway, I'm working on fixing this now.

**Comment by maebug** [comment]
I believe this was fixed within the past couple of commits.
