### ISSUE TITLE
Undefined block variable in GroupMenuBlock.php

### ISSUE THREAD

**Issue by misterjoonas** [awalacabab/group_menu#4]
`Notice: Undefined variable: build in Drupal\group_menu_block\Plugin\Block\GroupMenuBlock->build() (line 89 of modules/contrib/groupmenu/modules/group_menu_block/src/Plugin/Block/GroupMenuBlock.php). `

**Comment by maebug** [comment]
Well that was silly of me. I didn't initialize the array. *facepalm* Fixed now.
